app:
    resource: '@AppBundle/Controller/'
    type: annotation

index:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

geolocalisation:
    path:     /carte
    defaults: { _controller: AppBundle:Default:geolocalisation }